name: Check Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the PR creator
        run: echo "Pull request raised by ${{ github.event.pull_request.user.login }}"
