name: Check for merge conflicts
on:
  schedule:
    - cron: '* * * * *'  # This will run the action every day at midnight

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This is required to fetch all branches

      - name: Check for merge conflicts
        run: |
          git fetch origin main:main
          for branch in $(git branch -r | grep -v main); do
            git checkout $branch
            if git merge-base --is-ancestor main HEAD; then
              echo "No conflicts with $branch"
            else
              echo "Conflicts detected with $branch"
            fi
          done
