name: Check for Merge Conflicts (External Action)

on:
  pull_request:

jobs:
  detect-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: olivernybroe/action-conflict-finder@v2.0  # Replace with the desired version
