stages:
  - check_conflicts

jobs:
  check_conflicts:
    stage: check_conflicts
    script: |
      git fetch origin main:main
      git checkout main
      git merge --ff-only origin/$CI_MERGE_REQUEST_IID_SOURCE

      if [ $? -eq 0 ]; then
        echo "No merge conflicts detected."
      else
        echo "Merge conflicts detected! Please resolve them before merging."
        exit 1
      fi
