name: Check for Merge Conflicts

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_merge_conflicts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check for merge conflicts
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          if ! git merge --no-commit --no-ff origin/${{ github.event.pull_request.base.ref }}; then
            echo "::error::Merge conflict detected. Please resolve the conflicts and update the pull request."
            exit 1
          fi
