name: Check for Merge Conflicts

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Check for merge conflicts
      run: |
        git fetch origin +refs/heads/main:refs/remotes/origin/main
        git checkout ${{ github.head_ref }}
        if ! git merge --no-commit --no-ff origin/main; then
          echo "Merge conflict detected in PR #${{ github.event.pull_request.number }} on branch ${{ github.head_ref }}"
          exit 1
        fi
