name: Check for Merge Conflicts

on:
  pull_request:

jobs:
  detect-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files with merge conflict markers
        run: |
          git --no-pager grep "<<<<<<<" ":(exclude).github/" || true

      - name: Fail job if conflicts are found
        run: |
          if [ $(git grep "<<<<<<<" ":(exclude).github/" | wc -l) -gt 0 ]; then
            exit 1
          fi
