name: Check for merge conflicts
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: .pr

    - name: Check for merge conflicts
      run: |
        git fetch origin ${{ github.base_ref }}
        git fetch origin ${{ github.head_ref }}
        MERGE_BASE=$(git merge-base origin/${{ github.base_ref }} origin/${{ github.head_ref }})
        git merge-tree $MERGE_BASE origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -q 'changed in both'
        if [ $? -eq 0 ]; then
          echo "Merge conflict detected!"
          exit 1
        fi
